{{- if .Values.provisioner.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "porter.fullname" . }}-provisioner
  labels: {{- include "porter.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["jobs"]
    verbs: ["*"]
{{- end }}