apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "porter.fullname" . }}
  labels: {{- include "porter.labels" . | nindent 4 }}
rules:
  {{- if .Values.server.initInCluster }}
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
  - apiGroups: [""]
    resources: ["pods", "secrets", "configmaps", "pods/log", "pods/proxy", "pods/portforward", "pods/exec", "serviceaccounts", "services", "services/proxy"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "clusterroles", "rolebindings", "roles"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io", "extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["events.k8s.io", ""]
    resources: ["events"]
    verbs: ["*"]
  - apiGroups: ["metrics.k8s.io", ""]
    resources: ["nodes"]
    verbs: ["*"]
  {{- else }}
  []
  {{- end }}
