{{- if .Values.provisioner.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "porter.fullname" . }}-provisioner
  labels: {{- include "porter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "porter.fullname" . }}-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ include "porter.fullname" . }}-provisioner
    namespace: {{ .Release.Namespace }}
{{- end }}