{{- if .Values.workerPool.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "porter.fullname" . }}-worker-pool
  labels:
    {{- include "porter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "workerPool.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.workerPool.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "workerPool.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.workerPool.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "porter.fullname" . }}-worker-pool
      securityContext:
        {{- toYaml .Values.workerPool.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.workerPool.securityContext | nindent 12 }}
          image: "{{ .Values.workerPool.image.repository }}:{{ .Values.workerPool.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.workerPool.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.workerPool.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          env:
          - name: PORT
            value: "{{ .Values.workerPool.port }}"
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-api-server-keys
                key: db-encryption-key
          - name: SQL_LITE
            value: "false"
          - name: DB_PORT
            value: "5432"
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-db-secret
                key: host
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-db-secret
                key: name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-db-secret
                key: user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-db-secret
                key: password
          {{- range $key, $val := .Values.workerPool.env.normal }}
          - name: {{ $key }}
          {{- $splVal := split "_" $val -}}
          {{- if and (len $splVal | eq 2) (eq $splVal._0 "PORTERSECRET") }}
            valueFrom:
              secretKeyRef:
                name: {{ $splVal._1 }}
                key: {{ $key }}
          {{- else }}
            value: {{ quote $val }}
          {{- end }}
          {{- end }}
          {{- range $syncedEnv := .Values.workerPool.env.synced }}
          {{- range $key := $syncedEnv.keys }}
          - name: {{ $key.name }}
            {{- if $key.secret }}
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s.v%d" $syncedEnv.name ($syncedEnv.version | int) }}
                key: {{ $key.name }}
            {{- else }}
            valueFrom:
              configMapKeyRef:
                name: {{ printf "%s.v%d" $syncedEnv.name ($syncedEnv.version | int) }}
                key: {{ $key.name }}
            {{- end }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.workerPool.resources | nindent 12 }}
      {{- with .Values.workerPool.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workerPool.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workerPool.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}