{{- if and .Values.workerPool.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "porter.fullname" . }}-worker-pool
  labels:
    {{- include "porter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
