{{- if and .Values.provisioner.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "porter.fullname" . }}-provisioner
  labels:
    {{- include "porter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}