{{- if .Values.provisioner.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "porter.fullname" . }}-provisioner
  labels:
    {{- include "porter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.provisioner.service.type }}
  ports:
    - port: {{ .Values.provisioner.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "provisioner.selectorLabels" . | nindent 4 }}
{{- end }}